### ISSUE TITLE
Error running the ssh-config on OSX

### ISSUE THREAD

**Issue by cfredhart** [arr-dev/ssh-config#4]
I'm not sure if I'm using this as expected but, I get the error below.

```
TN4MACC02M82K4FH04:go charles.hart$ ssh-config google.com
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xf1740, 0xc4200120c0)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
main.(*Parser).Parse(0xc42004de70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/charles.hart/Documents/go/src/github.com/arr-dev/ssh-config/parser.go:45 +0x510
main.main()
    /Users/charles.hart/Documents/go/src/github.com/arr-dev/ssh-config/main.go:43 +0x32d
```

**Comment by arr-dev** [comment]
Hi, thanks for reporting.

Glad to see that someone else is using this.

Haven't tested on OSX, but I don't think it's an issue with OS, 
it seems to be with contents of `~/.ssh/config` file.

It would help if you would post contents of your `~/.ssh/config`, 
but considering it's private data, can't ask you to do that.

I'll try to add some guards in code to prevent this from happening.

Thanks again

**Comment by arr-dev** [comment]
Fixed in ade5d70fe78871f23397c859b0e941bad297ffe4

@cfredhart can you try again with version from master?

**Comment by cfredhart** [comment]
Thanks! That fixed it.

**Comment by arr-dev** [comment]
Great, thanks for reporting it.
